/**
 * Firebase client SDK initialization and utility functions for authentication.
 * This module sets up the Firebase client SDK for a web (Next.js) app and
 * provides helpers to enable TOTP (Google Authenticator) MFA and to retrieve
 * a custom token with RBAC role claims.
 */

import { initializeApp, getApps, getApp } from 'firebase/app';
import { getAuth, multiFactor, TotpSecret, TotpMultiFactorGenerator, EmailAuthProvider, signInWithEmailAndPassword } from 'firebase/auth';
import { getFirestore } from 'firebase/firestore/lite';

// Initialize Firebase App using environment variables with config fallback.
const firebaseConfig = {
  apiKey: process.env.NEXT_PUBLIC_FIREBASE_API_KEY || "AIzaSyCPeAOWQj8456TeIWDIPsyxyWT7QLrC8J8",
  authDomain: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN || "ai-foundation-firebase.firebaseapp.com",
  projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID || "ai-foundation-firebase",
  storageBucket: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET || "ai-foundation-firebase.firebasestorage.app",
  messagingSenderId: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID || "614773274800",
  appId: process.env.NEXT_PUBLIC_FIREBASE_APP_ID || "1:614773274800:web:bcfa9d363de884cf9ea375"
};

const app = !getApps().length ? initializeApp(firebaseConfig) : getApp();
export const auth = getAuth(app);
export const db = getFirestore(app);

/**
 * Enroll the signed‑in user in TOTP MFA using Google Authenticator.
 *
 * This flow follows the Firebase Auth client‑side enrollment process:
 *   1. The user signs in with a primary provider (e.g., email/password).
 *   2. Call `multiFactor(auth.currentUser!).enroll` with a `TotpSecret`
 *      generated by the server (via the admin SDK) or by the client using
 *      `TotpMultiFactorGenerator.generateSecret()`.
 *   3. Display the QR code to the user and verify the TOTP code.
 */
export async function enrollCurrentUserInTotp() {
  if (!auth.currentUser) {
    throw new Error('No user is currently signed in');
  }

  // Generate a new TOTP secret (the secret can also be fetched from the server).
  const secret: TotpSecret = await TotpMultiFactorGenerator.generateSecret(auth);

  // Enroll the user with the secret.
  const assertion = TotpMultiFactorGenerator.assertionForEnrollment(secret, '000000');
  const enrollment = await multiFactor(auth.currentUser).enroll(assertion, 'Google Authenticator');

  // The `enrollment` contains a `verificationCode` that the user must provide.
  // The UI should prompt the user to enter the 6‑digit code generated by the
  // authenticator app. Once verified, the MFA factor is active.
  return enrollment;
}

/**
 * Sign‑in with email and password and request a fresh ID token that includes
 * custom claims (RBAC role claims) set by the admin SDK.
 */
export async function signInAndRefreshToken(email: string, password: string) {
  const userCredential = await signInWithEmailAndPassword(auth, email, password);
  // Force token refresh to include custom claims.
  const idToken = await userCredential.user.getIdToken(true);
  return idToken;
}

export { app };
